// source: ide.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

goog.exportSymbol('proto.idepb.EmptyMessage', null, global);
goog.exportSymbol('proto.idepb.ErrorResponse', null, global);
goog.exportSymbol('proto.idepb.FindStringRequest', null, global);
goog.exportSymbol('proto.idepb.FindStringResponse', null, global);
goog.exportSymbol('proto.idepb.GetFilesRequest', null, global);
goog.exportSymbol('proto.idepb.GetFilesResponse', null, global);
goog.exportSymbol('proto.idepb.ListFilesRequest', null, global);
goog.exportSymbol('proto.idepb.ListFilesResponse', null, global);
goog.exportSymbol('proto.idepb.Location', null, global);
goog.exportSymbol('proto.idepb.OpenFilesRequest', null, global);
goog.exportSymbol('proto.idepb.OpenFilesResponse', null, global);
goog.exportSymbol('proto.idepb.Position', null, global);
goog.exportSymbol('proto.idepb.RequestMessage', null, global);
goog.exportSymbol('proto.idepb.RequestMessage.DataCase', null, global);
goog.exportSymbol('proto.idepb.RequestType', null, global);
goog.exportSymbol('proto.idepb.ResponseMessage', null, global);
goog.exportSymbol('proto.idepb.ResponseMessage.DataCase', null, global);
goog.exportSymbol('proto.idepb.ResponseType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idepb.EmptyMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idepb.EmptyMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idepb.EmptyMessage.displayName = 'proto.idepb.EmptyMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idepb.ListFilesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.idepb.ListFilesRequest.repeatedFields_, null);
};
goog.inherits(proto.idepb.ListFilesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idepb.ListFilesRequest.displayName = 'proto.idepb.ListFilesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idepb.OpenFilesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.idepb.OpenFilesRequest.repeatedFields_, null);
};
goog.inherits(proto.idepb.OpenFilesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idepb.OpenFilesRequest.displayName = 'proto.idepb.OpenFilesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idepb.GetFilesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.idepb.GetFilesRequest.repeatedFields_, null);
};
goog.inherits(proto.idepb.GetFilesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idepb.GetFilesRequest.displayName = 'proto.idepb.GetFilesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idepb.FindStringRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.idepb.FindStringRequest.repeatedFields_, null);
};
goog.inherits(proto.idepb.FindStringRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idepb.FindStringRequest.displayName = 'proto.idepb.FindStringRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idepb.RequestMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.idepb.RequestMessage.oneofGroups_);
};
goog.inherits(proto.idepb.RequestMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idepb.RequestMessage.displayName = 'proto.idepb.RequestMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idepb.ListFilesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.idepb.ListFilesResponse.repeatedFields_, null);
};
goog.inherits(proto.idepb.ListFilesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idepb.ListFilesResponse.displayName = 'proto.idepb.ListFilesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idepb.OpenFilesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idepb.OpenFilesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idepb.OpenFilesResponse.displayName = 'proto.idepb.OpenFilesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idepb.GetFilesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.idepb.GetFilesResponse.repeatedFields_, null);
};
goog.inherits(proto.idepb.GetFilesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idepb.GetFilesResponse.displayName = 'proto.idepb.GetFilesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idepb.Position = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idepb.Position, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idepb.Position.displayName = 'proto.idepb.Position';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idepb.Location = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idepb.Location, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idepb.Location.displayName = 'proto.idepb.Location';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idepb.FindStringResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.idepb.FindStringResponse.repeatedFields_, null);
};
goog.inherits(proto.idepb.FindStringResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idepb.FindStringResponse.displayName = 'proto.idepb.FindStringResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idepb.ErrorResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.idepb.ErrorResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idepb.ErrorResponse.displayName = 'proto.idepb.ErrorResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.idepb.ResponseMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.idepb.ResponseMessage.oneofGroups_);
};
goog.inherits(proto.idepb.ResponseMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.idepb.ResponseMessage.displayName = 'proto.idepb.ResponseMessage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idepb.EmptyMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.idepb.EmptyMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idepb.EmptyMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.EmptyMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    debug: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idepb.EmptyMessage}
 */
proto.idepb.EmptyMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idepb.EmptyMessage;
  return proto.idepb.EmptyMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idepb.EmptyMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idepb.EmptyMessage}
 */
proto.idepb.EmptyMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDebug(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idepb.EmptyMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idepb.EmptyMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idepb.EmptyMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.EmptyMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDebug();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string debug = 1;
 * @return {string}
 */
proto.idepb.EmptyMessage.prototype.getDebug = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.idepb.EmptyMessage} returns this
 */
proto.idepb.EmptyMessage.prototype.setDebug = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idepb.ListFilesRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idepb.ListFilesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.idepb.ListFilesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idepb.ListFilesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.ListFilesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    excludedDirList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idepb.ListFilesRequest}
 */
proto.idepb.ListFilesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idepb.ListFilesRequest;
  return proto.idepb.ListFilesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idepb.ListFilesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idepb.ListFilesRequest}
 */
proto.idepb.ListFilesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addExcludedDir(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idepb.ListFilesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idepb.ListFilesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idepb.ListFilesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.ListFilesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getExcludedDirList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string excluded_dir = 1;
 * @return {!Array<string>}
 */
proto.idepb.ListFilesRequest.prototype.getExcludedDirList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.idepb.ListFilesRequest} returns this
 */
proto.idepb.ListFilesRequest.prototype.setExcludedDirList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.idepb.ListFilesRequest} returns this
 */
proto.idepb.ListFilesRequest.prototype.addExcludedDir = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idepb.ListFilesRequest} returns this
 */
proto.idepb.ListFilesRequest.prototype.clearExcludedDirList = function() {
  return this.setExcludedDirList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idepb.OpenFilesRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idepb.OpenFilesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.idepb.OpenFilesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idepb.OpenFilesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.OpenFilesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    filePathsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idepb.OpenFilesRequest}
 */
proto.idepb.OpenFilesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idepb.OpenFilesRequest;
  return proto.idepb.OpenFilesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idepb.OpenFilesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idepb.OpenFilesRequest}
 */
proto.idepb.OpenFilesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addFilePaths(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idepb.OpenFilesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idepb.OpenFilesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idepb.OpenFilesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.OpenFilesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilePathsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string file_paths = 1;
 * @return {!Array<string>}
 */
proto.idepb.OpenFilesRequest.prototype.getFilePathsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.idepb.OpenFilesRequest} returns this
 */
proto.idepb.OpenFilesRequest.prototype.setFilePathsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.idepb.OpenFilesRequest} returns this
 */
proto.idepb.OpenFilesRequest.prototype.addFilePaths = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idepb.OpenFilesRequest} returns this
 */
proto.idepb.OpenFilesRequest.prototype.clearFilePathsList = function() {
  return this.setFilePathsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idepb.GetFilesRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idepb.GetFilesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.idepb.GetFilesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idepb.GetFilesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.GetFilesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    filePathsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idepb.GetFilesRequest}
 */
proto.idepb.GetFilesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idepb.GetFilesRequest;
  return proto.idepb.GetFilesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idepb.GetFilesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idepb.GetFilesRequest}
 */
proto.idepb.GetFilesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addFilePaths(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idepb.GetFilesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idepb.GetFilesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idepb.GetFilesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.GetFilesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilePathsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string file_paths = 1;
 * @return {!Array<string>}
 */
proto.idepb.GetFilesRequest.prototype.getFilePathsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.idepb.GetFilesRequest} returns this
 */
proto.idepb.GetFilesRequest.prototype.setFilePathsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.idepb.GetFilesRequest} returns this
 */
proto.idepb.GetFilesRequest.prototype.addFilePaths = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idepb.GetFilesRequest} returns this
 */
proto.idepb.GetFilesRequest.prototype.clearFilePathsList = function() {
  return this.setFilePathsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idepb.FindStringRequest.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idepb.FindStringRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.idepb.FindStringRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idepb.FindStringRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.FindStringRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    searchPattern: jspb.Message.getFieldWithDefault(msg, 1, ""),
    includedFilesList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f,
    excludedFilesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idepb.FindStringRequest}
 */
proto.idepb.FindStringRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idepb.FindStringRequest;
  return proto.idepb.FindStringRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idepb.FindStringRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idepb.FindStringRequest}
 */
proto.idepb.FindStringRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSearchPattern(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addIncludedFiles(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addExcludedFiles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idepb.FindStringRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idepb.FindStringRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idepb.FindStringRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.FindStringRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSearchPattern();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIncludedFilesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
  f = message.getExcludedFilesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * optional string search_pattern = 1;
 * @return {string}
 */
proto.idepb.FindStringRequest.prototype.getSearchPattern = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.idepb.FindStringRequest} returns this
 */
proto.idepb.FindStringRequest.prototype.setSearchPattern = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string included_files = 2;
 * @return {!Array<string>}
 */
proto.idepb.FindStringRequest.prototype.getIncludedFilesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.idepb.FindStringRequest} returns this
 */
proto.idepb.FindStringRequest.prototype.setIncludedFilesList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.idepb.FindStringRequest} returns this
 */
proto.idepb.FindStringRequest.prototype.addIncludedFiles = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idepb.FindStringRequest} returns this
 */
proto.idepb.FindStringRequest.prototype.clearIncludedFilesList = function() {
  return this.setIncludedFilesList([]);
};


/**
 * repeated string excluded_files = 3;
 * @return {!Array<string>}
 */
proto.idepb.FindStringRequest.prototype.getExcludedFilesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.idepb.FindStringRequest} returns this
 */
proto.idepb.FindStringRequest.prototype.setExcludedFilesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.idepb.FindStringRequest} returns this
 */
proto.idepb.FindStringRequest.prototype.addExcludedFiles = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idepb.FindStringRequest} returns this
 */
proto.idepb.FindStringRequest.prototype.clearExcludedFilesList = function() {
  return this.setExcludedFilesList([]);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.idepb.RequestMessage.oneofGroups_ = [[3,4,5,6]];

/**
 * @enum {number}
 */
proto.idepb.RequestMessage.DataCase = {
  DATA_NOT_SET: 0,
  LIST_FILES: 3,
  GET_FILES: 4,
  OPEN_FILES: 5,
  FIND_STRING: 6
};

/**
 * @return {proto.idepb.RequestMessage.DataCase}
 */
proto.idepb.RequestMessage.prototype.getDataCase = function() {
  return /** @type {proto.idepb.RequestMessage.DataCase} */(jspb.Message.computeOneofCase(this, proto.idepb.RequestMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idepb.RequestMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.idepb.RequestMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idepb.RequestMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.RequestMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    commandId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    listFiles: (f = msg.getListFiles()) && proto.idepb.ListFilesRequest.toObject(includeInstance, f),
    getFiles: (f = msg.getGetFiles()) && proto.idepb.GetFilesRequest.toObject(includeInstance, f),
    openFiles: (f = msg.getOpenFiles()) && proto.idepb.OpenFilesRequest.toObject(includeInstance, f),
    findString: (f = msg.getFindString()) && proto.idepb.FindStringRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idepb.RequestMessage}
 */
proto.idepb.RequestMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idepb.RequestMessage;
  return proto.idepb.RequestMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idepb.RequestMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idepb.RequestMessage}
 */
proto.idepb.RequestMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.idepb.RequestType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCommandId(value);
      break;
    case 3:
      var value = new proto.idepb.ListFilesRequest;
      reader.readMessage(value,proto.idepb.ListFilesRequest.deserializeBinaryFromReader);
      msg.setListFiles(value);
      break;
    case 4:
      var value = new proto.idepb.GetFilesRequest;
      reader.readMessage(value,proto.idepb.GetFilesRequest.deserializeBinaryFromReader);
      msg.setGetFiles(value);
      break;
    case 5:
      var value = new proto.idepb.OpenFilesRequest;
      reader.readMessage(value,proto.idepb.OpenFilesRequest.deserializeBinaryFromReader);
      msg.setOpenFiles(value);
      break;
    case 6:
      var value = new proto.idepb.FindStringRequest;
      reader.readMessage(value,proto.idepb.FindStringRequest.deserializeBinaryFromReader);
      msg.setFindString(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idepb.RequestMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idepb.RequestMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idepb.RequestMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.RequestMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCommandId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getListFiles();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.idepb.ListFilesRequest.serializeBinaryToWriter
    );
  }
  f = message.getGetFiles();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.idepb.GetFilesRequest.serializeBinaryToWriter
    );
  }
  f = message.getOpenFiles();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.idepb.OpenFilesRequest.serializeBinaryToWriter
    );
  }
  f = message.getFindString();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.idepb.FindStringRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional RequestType type = 1;
 * @return {!proto.idepb.RequestType}
 */
proto.idepb.RequestMessage.prototype.getType = function() {
  return /** @type {!proto.idepb.RequestType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.idepb.RequestType} value
 * @return {!proto.idepb.RequestMessage} returns this
 */
proto.idepb.RequestMessage.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string command_id = 2;
 * @return {string}
 */
proto.idepb.RequestMessage.prototype.getCommandId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.idepb.RequestMessage} returns this
 */
proto.idepb.RequestMessage.prototype.setCommandId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional ListFilesRequest list_files = 3;
 * @return {?proto.idepb.ListFilesRequest}
 */
proto.idepb.RequestMessage.prototype.getListFiles = function() {
  return /** @type{?proto.idepb.ListFilesRequest} */ (
    jspb.Message.getWrapperField(this, proto.idepb.ListFilesRequest, 3));
};


/**
 * @param {?proto.idepb.ListFilesRequest|undefined} value
 * @return {!proto.idepb.RequestMessage} returns this
*/
proto.idepb.RequestMessage.prototype.setListFiles = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.idepb.RequestMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.idepb.RequestMessage} returns this
 */
proto.idepb.RequestMessage.prototype.clearListFiles = function() {
  return this.setListFiles(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idepb.RequestMessage.prototype.hasListFiles = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional GetFilesRequest get_files = 4;
 * @return {?proto.idepb.GetFilesRequest}
 */
proto.idepb.RequestMessage.prototype.getGetFiles = function() {
  return /** @type{?proto.idepb.GetFilesRequest} */ (
    jspb.Message.getWrapperField(this, proto.idepb.GetFilesRequest, 4));
};


/**
 * @param {?proto.idepb.GetFilesRequest|undefined} value
 * @return {!proto.idepb.RequestMessage} returns this
*/
proto.idepb.RequestMessage.prototype.setGetFiles = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.idepb.RequestMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.idepb.RequestMessage} returns this
 */
proto.idepb.RequestMessage.prototype.clearGetFiles = function() {
  return this.setGetFiles(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idepb.RequestMessage.prototype.hasGetFiles = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional OpenFilesRequest open_files = 5;
 * @return {?proto.idepb.OpenFilesRequest}
 */
proto.idepb.RequestMessage.prototype.getOpenFiles = function() {
  return /** @type{?proto.idepb.OpenFilesRequest} */ (
    jspb.Message.getWrapperField(this, proto.idepb.OpenFilesRequest, 5));
};


/**
 * @param {?proto.idepb.OpenFilesRequest|undefined} value
 * @return {!proto.idepb.RequestMessage} returns this
*/
proto.idepb.RequestMessage.prototype.setOpenFiles = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.idepb.RequestMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.idepb.RequestMessage} returns this
 */
proto.idepb.RequestMessage.prototype.clearOpenFiles = function() {
  return this.setOpenFiles(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idepb.RequestMessage.prototype.hasOpenFiles = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional FindStringRequest find_string = 6;
 * @return {?proto.idepb.FindStringRequest}
 */
proto.idepb.RequestMessage.prototype.getFindString = function() {
  return /** @type{?proto.idepb.FindStringRequest} */ (
    jspb.Message.getWrapperField(this, proto.idepb.FindStringRequest, 6));
};


/**
 * @param {?proto.idepb.FindStringRequest|undefined} value
 * @return {!proto.idepb.RequestMessage} returns this
*/
proto.idepb.RequestMessage.prototype.setFindString = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.idepb.RequestMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.idepb.RequestMessage} returns this
 */
proto.idepb.RequestMessage.prototype.clearFindString = function() {
  return this.setFindString(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idepb.RequestMessage.prototype.hasFindString = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idepb.ListFilesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idepb.ListFilesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.idepb.ListFilesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idepb.ListFilesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.ListFilesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    filePathsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idepb.ListFilesResponse}
 */
proto.idepb.ListFilesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idepb.ListFilesResponse;
  return proto.idepb.ListFilesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idepb.ListFilesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idepb.ListFilesResponse}
 */
proto.idepb.ListFilesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addFilePaths(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idepb.ListFilesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idepb.ListFilesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idepb.ListFilesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.ListFilesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilePathsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string file_paths = 1;
 * @return {!Array<string>}
 */
proto.idepb.ListFilesResponse.prototype.getFilePathsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.idepb.ListFilesResponse} returns this
 */
proto.idepb.ListFilesResponse.prototype.setFilePathsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.idepb.ListFilesResponse} returns this
 */
proto.idepb.ListFilesResponse.prototype.addFilePaths = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idepb.ListFilesResponse} returns this
 */
proto.idepb.ListFilesResponse.prototype.clearFilePathsList = function() {
  return this.setFilePathsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idepb.OpenFilesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.idepb.OpenFilesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idepb.OpenFilesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.OpenFilesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idepb.OpenFilesResponse}
 */
proto.idepb.OpenFilesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idepb.OpenFilesResponse;
  return proto.idepb.OpenFilesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idepb.OpenFilesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idepb.OpenFilesResponse}
 */
proto.idepb.OpenFilesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idepb.OpenFilesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idepb.OpenFilesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idepb.OpenFilesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.OpenFilesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idepb.GetFilesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idepb.GetFilesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.idepb.GetFilesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idepb.GetFilesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.GetFilesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fileContentsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idepb.GetFilesResponse}
 */
proto.idepb.GetFilesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idepb.GetFilesResponse;
  return proto.idepb.GetFilesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idepb.GetFilesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idepb.GetFilesResponse}
 */
proto.idepb.GetFilesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addFileContents(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idepb.GetFilesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idepb.GetFilesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idepb.GetFilesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.GetFilesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFileContentsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string file_contents = 1;
 * @return {!Array<string>}
 */
proto.idepb.GetFilesResponse.prototype.getFileContentsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.idepb.GetFilesResponse} returns this
 */
proto.idepb.GetFilesResponse.prototype.setFileContentsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.idepb.GetFilesResponse} returns this
 */
proto.idepb.GetFilesResponse.prototype.addFileContents = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idepb.GetFilesResponse} returns this
 */
proto.idepb.GetFilesResponse.prototype.clearFileContentsList = function() {
  return this.setFileContentsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idepb.Position.prototype.toObject = function(opt_includeInstance) {
  return proto.idepb.Position.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idepb.Position} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.Position.toObject = function(includeInstance, msg) {
  var f, obj = {
    line: jspb.Message.getFieldWithDefault(msg, 1, 0),
    character: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idepb.Position}
 */
proto.idepb.Position.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idepb.Position;
  return proto.idepb.Position.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idepb.Position} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idepb.Position}
 */
proto.idepb.Position.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setLine(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCharacter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idepb.Position.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idepb.Position.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idepb.Position} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.Position.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLine();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getCharacter();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional int64 line = 1;
 * @return {number}
 */
proto.idepb.Position.prototype.getLine = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.idepb.Position} returns this
 */
proto.idepb.Position.prototype.setLine = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 character = 2;
 * @return {number}
 */
proto.idepb.Position.prototype.getCharacter = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.idepb.Position} returns this
 */
proto.idepb.Position.prototype.setCharacter = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idepb.Location.prototype.toObject = function(opt_includeInstance) {
  return proto.idepb.Location.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idepb.Location} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.Location.toObject = function(includeInstance, msg) {
  var f, obj = {
    path: jspb.Message.getFieldWithDefault(msg, 1, ""),
    start: (f = msg.getStart()) && proto.idepb.Position.toObject(includeInstance, f),
    end: (f = msg.getEnd()) && proto.idepb.Position.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idepb.Location}
 */
proto.idepb.Location.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idepb.Location;
  return proto.idepb.Location.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idepb.Location} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idepb.Location}
 */
proto.idepb.Location.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 2:
      var value = new proto.idepb.Position;
      reader.readMessage(value,proto.idepb.Position.deserializeBinaryFromReader);
      msg.setStart(value);
      break;
    case 3:
      var value = new proto.idepb.Position;
      reader.readMessage(value,proto.idepb.Position.deserializeBinaryFromReader);
      msg.setEnd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idepb.Location.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idepb.Location.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idepb.Location} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.Location.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStart();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.idepb.Position.serializeBinaryToWriter
    );
  }
  f = message.getEnd();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.idepb.Position.serializeBinaryToWriter
    );
  }
};


/**
 * optional string path = 1;
 * @return {string}
 */
proto.idepb.Location.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.idepb.Location} returns this
 */
proto.idepb.Location.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional Position start = 2;
 * @return {?proto.idepb.Position}
 */
proto.idepb.Location.prototype.getStart = function() {
  return /** @type{?proto.idepb.Position} */ (
    jspb.Message.getWrapperField(this, proto.idepb.Position, 2));
};


/**
 * @param {?proto.idepb.Position|undefined} value
 * @return {!proto.idepb.Location} returns this
*/
proto.idepb.Location.prototype.setStart = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.idepb.Location} returns this
 */
proto.idepb.Location.prototype.clearStart = function() {
  return this.setStart(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idepb.Location.prototype.hasStart = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Position end = 3;
 * @return {?proto.idepb.Position}
 */
proto.idepb.Location.prototype.getEnd = function() {
  return /** @type{?proto.idepb.Position} */ (
    jspb.Message.getWrapperField(this, proto.idepb.Position, 3));
};


/**
 * @param {?proto.idepb.Position|undefined} value
 * @return {!proto.idepb.Location} returns this
*/
proto.idepb.Location.prototype.setEnd = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.idepb.Location} returns this
 */
proto.idepb.Location.prototype.clearEnd = function() {
  return this.setEnd(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idepb.Location.prototype.hasEnd = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.idepb.FindStringResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idepb.FindStringResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.idepb.FindStringResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idepb.FindStringResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.FindStringResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    locationsList: jspb.Message.toObjectList(msg.getLocationsList(),
    proto.idepb.Location.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idepb.FindStringResponse}
 */
proto.idepb.FindStringResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idepb.FindStringResponse;
  return proto.idepb.FindStringResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idepb.FindStringResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idepb.FindStringResponse}
 */
proto.idepb.FindStringResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.idepb.Location;
      reader.readMessage(value,proto.idepb.Location.deserializeBinaryFromReader);
      msg.addLocations(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idepb.FindStringResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idepb.FindStringResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idepb.FindStringResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.FindStringResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLocationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.idepb.Location.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Location locations = 1;
 * @return {!Array<!proto.idepb.Location>}
 */
proto.idepb.FindStringResponse.prototype.getLocationsList = function() {
  return /** @type{!Array<!proto.idepb.Location>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.idepb.Location, 1));
};


/**
 * @param {!Array<!proto.idepb.Location>} value
 * @return {!proto.idepb.FindStringResponse} returns this
*/
proto.idepb.FindStringResponse.prototype.setLocationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.idepb.Location=} opt_value
 * @param {number=} opt_index
 * @return {!proto.idepb.Location}
 */
proto.idepb.FindStringResponse.prototype.addLocations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.idepb.Location, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.idepb.FindStringResponse} returns this
 */
proto.idepb.FindStringResponse.prototype.clearLocationsList = function() {
  return this.setLocationsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idepb.ErrorResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.idepb.ErrorResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idepb.ErrorResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.ErrorResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idepb.ErrorResponse}
 */
proto.idepb.ErrorResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idepb.ErrorResponse;
  return proto.idepb.ErrorResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idepb.ErrorResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idepb.ErrorResponse}
 */
proto.idepb.ErrorResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idepb.ErrorResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idepb.ErrorResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idepb.ErrorResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.ErrorResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getError();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string error = 1;
 * @return {string}
 */
proto.idepb.ErrorResponse.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.idepb.ErrorResponse} returns this
 */
proto.idepb.ErrorResponse.prototype.setError = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.idepb.ResponseMessage.oneofGroups_ = [[3,4,5,6,7]];

/**
 * @enum {number}
 */
proto.idepb.ResponseMessage.DataCase = {
  DATA_NOT_SET: 0,
  ERROR: 3,
  LIST_FILES: 4,
  GET_FILES: 5,
  OPEN_FILES: 6,
  FIND: 7
};

/**
 * @return {proto.idepb.ResponseMessage.DataCase}
 */
proto.idepb.ResponseMessage.prototype.getDataCase = function() {
  return /** @type {proto.idepb.ResponseMessage.DataCase} */(jspb.Message.computeOneofCase(this, proto.idepb.ResponseMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.idepb.ResponseMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.idepb.ResponseMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.idepb.ResponseMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.ResponseMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    commandId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    error: (f = msg.getError()) && proto.idepb.ErrorResponse.toObject(includeInstance, f),
    listFiles: (f = msg.getListFiles()) && proto.idepb.ListFilesResponse.toObject(includeInstance, f),
    getFiles: (f = msg.getGetFiles()) && proto.idepb.GetFilesResponse.toObject(includeInstance, f),
    openFiles: (f = msg.getOpenFiles()) && proto.idepb.OpenFilesResponse.toObject(includeInstance, f),
    find: (f = msg.getFind()) && proto.idepb.FindStringResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.idepb.ResponseMessage}
 */
proto.idepb.ResponseMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.idepb.ResponseMessage;
  return proto.idepb.ResponseMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.idepb.ResponseMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.idepb.ResponseMessage}
 */
proto.idepb.ResponseMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.idepb.ResponseType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCommandId(value);
      break;
    case 3:
      var value = new proto.idepb.ErrorResponse;
      reader.readMessage(value,proto.idepb.ErrorResponse.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    case 4:
      var value = new proto.idepb.ListFilesResponse;
      reader.readMessage(value,proto.idepb.ListFilesResponse.deserializeBinaryFromReader);
      msg.setListFiles(value);
      break;
    case 5:
      var value = new proto.idepb.GetFilesResponse;
      reader.readMessage(value,proto.idepb.GetFilesResponse.deserializeBinaryFromReader);
      msg.setGetFiles(value);
      break;
    case 6:
      var value = new proto.idepb.OpenFilesResponse;
      reader.readMessage(value,proto.idepb.OpenFilesResponse.deserializeBinaryFromReader);
      msg.setOpenFiles(value);
      break;
    case 7:
      var value = new proto.idepb.FindStringResponse;
      reader.readMessage(value,proto.idepb.FindStringResponse.deserializeBinaryFromReader);
      msg.setFind(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.idepb.ResponseMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.idepb.ResponseMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.idepb.ResponseMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.idepb.ResponseMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getCommandId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.idepb.ErrorResponse.serializeBinaryToWriter
    );
  }
  f = message.getListFiles();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.idepb.ListFilesResponse.serializeBinaryToWriter
    );
  }
  f = message.getGetFiles();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.idepb.GetFilesResponse.serializeBinaryToWriter
    );
  }
  f = message.getOpenFiles();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.idepb.OpenFilesResponse.serializeBinaryToWriter
    );
  }
  f = message.getFind();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.idepb.FindStringResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional ResponseType type = 1;
 * @return {!proto.idepb.ResponseType}
 */
proto.idepb.ResponseMessage.prototype.getType = function() {
  return /** @type {!proto.idepb.ResponseType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.idepb.ResponseType} value
 * @return {!proto.idepb.ResponseMessage} returns this
 */
proto.idepb.ResponseMessage.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string command_id = 2;
 * @return {string}
 */
proto.idepb.ResponseMessage.prototype.getCommandId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.idepb.ResponseMessage} returns this
 */
proto.idepb.ResponseMessage.prototype.setCommandId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional ErrorResponse error = 3;
 * @return {?proto.idepb.ErrorResponse}
 */
proto.idepb.ResponseMessage.prototype.getError = function() {
  return /** @type{?proto.idepb.ErrorResponse} */ (
    jspb.Message.getWrapperField(this, proto.idepb.ErrorResponse, 3));
};


/**
 * @param {?proto.idepb.ErrorResponse|undefined} value
 * @return {!proto.idepb.ResponseMessage} returns this
*/
proto.idepb.ResponseMessage.prototype.setError = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.idepb.ResponseMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.idepb.ResponseMessage} returns this
 */
proto.idepb.ResponseMessage.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idepb.ResponseMessage.prototype.hasError = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ListFilesResponse list_files = 4;
 * @return {?proto.idepb.ListFilesResponse}
 */
proto.idepb.ResponseMessage.prototype.getListFiles = function() {
  return /** @type{?proto.idepb.ListFilesResponse} */ (
    jspb.Message.getWrapperField(this, proto.idepb.ListFilesResponse, 4));
};


/**
 * @param {?proto.idepb.ListFilesResponse|undefined} value
 * @return {!proto.idepb.ResponseMessage} returns this
*/
proto.idepb.ResponseMessage.prototype.setListFiles = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.idepb.ResponseMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.idepb.ResponseMessage} returns this
 */
proto.idepb.ResponseMessage.prototype.clearListFiles = function() {
  return this.setListFiles(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idepb.ResponseMessage.prototype.hasListFiles = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional GetFilesResponse get_files = 5;
 * @return {?proto.idepb.GetFilesResponse}
 */
proto.idepb.ResponseMessage.prototype.getGetFiles = function() {
  return /** @type{?proto.idepb.GetFilesResponse} */ (
    jspb.Message.getWrapperField(this, proto.idepb.GetFilesResponse, 5));
};


/**
 * @param {?proto.idepb.GetFilesResponse|undefined} value
 * @return {!proto.idepb.ResponseMessage} returns this
*/
proto.idepb.ResponseMessage.prototype.setGetFiles = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.idepb.ResponseMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.idepb.ResponseMessage} returns this
 */
proto.idepb.ResponseMessage.prototype.clearGetFiles = function() {
  return this.setGetFiles(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idepb.ResponseMessage.prototype.hasGetFiles = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional OpenFilesResponse open_files = 6;
 * @return {?proto.idepb.OpenFilesResponse}
 */
proto.idepb.ResponseMessage.prototype.getOpenFiles = function() {
  return /** @type{?proto.idepb.OpenFilesResponse} */ (
    jspb.Message.getWrapperField(this, proto.idepb.OpenFilesResponse, 6));
};


/**
 * @param {?proto.idepb.OpenFilesResponse|undefined} value
 * @return {!proto.idepb.ResponseMessage} returns this
*/
proto.idepb.ResponseMessage.prototype.setOpenFiles = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.idepb.ResponseMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.idepb.ResponseMessage} returns this
 */
proto.idepb.ResponseMessage.prototype.clearOpenFiles = function() {
  return this.setOpenFiles(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idepb.ResponseMessage.prototype.hasOpenFiles = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional FindStringResponse find = 7;
 * @return {?proto.idepb.FindStringResponse}
 */
proto.idepb.ResponseMessage.prototype.getFind = function() {
  return /** @type{?proto.idepb.FindStringResponse} */ (
    jspb.Message.getWrapperField(this, proto.idepb.FindStringResponse, 7));
};


/**
 * @param {?proto.idepb.FindStringResponse|undefined} value
 * @return {!proto.idepb.ResponseMessage} returns this
*/
proto.idepb.ResponseMessage.prototype.setFind = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.idepb.ResponseMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.idepb.ResponseMessage} returns this
 */
proto.idepb.ResponseMessage.prototype.clearFind = function() {
  return this.setFind(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.idepb.ResponseMessage.prototype.hasFind = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * @enum {number}
 */
proto.idepb.RequestType = {
  REQUEST_INVALID: 0,
  REQUEST_LIST_FILES: 1,
  REQUEST_GET_FILES: 2,
  REQUEST_OPEN_FILES: 3,
  REQUEST_FIND_STRING: 4
};

/**
 * @enum {number}
 */
proto.idepb.ResponseType = {
  RESPONSE_INVALID: 0,
  RESPONSE_ERROR: 1,
  RESPONSE_LIST_FILES: 2,
  RESPONSE_GET_FILES: 3,
  RESPONSE_OPEN_FILES: 4,
  RESPONSE_FIND_STRING: 5
};

goog.object.extend(exports, proto.idepb);
